repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|ts|tsx|json|md|yaml|yml)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        additional_dependencies:
          - eslint@8.56.0
          - typescript@5.3.3
          - "@typescript-eslint/parser@6.19.0"
          - "@typescript-eslint/eslint-plugin@6.19.0"

  - repo: local
    hooks:
      - id: typecheck
        name: TypeScript Type Check
        entry: npm run typecheck
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$

      - id: test
        name: Run Tests
        entry: npm test -- --passWithNoTests
        language: system
        pass_filenames: false
        files: \.(ts|tsx|js)$